In [1]:
import pandas as pd

'disbalanced_binary_tasks': [3021, 3902, 3903, 3904, 3913, 3917, 3918, 7592, 9952, 9971, 9977, 9978, 10101], 
'balanced_binary_tasks': [3, 15, 29, 31, 37, 43, 49, 219, 9910, 9946, 9957, 9976, 10093, 14952], 
'multiclass_tasks': [6, 11, 12, 14, 16, 18, 22, 23, 28, 32, 45, 53, 2074, 2079, 3022, 3481, 3549, 3560, 3573]

In [33]:
df = pd.read_csv('/home/robert/gitClones/cc18-analysis/evaluation/csv_results/combined_metrics.csv')
df_n3 = df[df['neighbours'] == 3]
df_n7 = df[df['neighbours'] == 7]
df_n11 = df[df['neighbours'] == 11]
df.head(20)

    dataset  neighbours  accuracy_sk   accuracy_mod  roc_auc_sk  roc_auc_mod
0        31           3     0.619000       0.631000    0.514524     0.524048
1        31           7     0.652000       0.656000    0.524762     0.522857
2        31          11     0.664000       0.669000    0.521905     0.531190
3        37           3     0.700478       0.811176    0.666282     0.781667
4        37           7     0.737030       0.817772    0.690732     0.784254
5        37          11     0.738295       0.819036    0.693293     0.787738
6        43           3     0.799398       0.804612    0.791289     0.784519
7        43           7     0.801137       0.799180    0.792821     0.777325
8        43          11     0.793534       0.802007    0.783759     0.779364
9      3902           3     0.851871       0.863496    0.555527     0.578715
10     3902           7     0.862839       0.862140    0.520379     0.500564
11     3902          11     0.866949       0.871752    0.515561     0.498872
12     3903           3     0.866279       0.871387    0.568367     0.546293
13     3903           7     0.889940       0.888025    0.551089     0.538949
14     3903          11     0.893157       0.889956    0.533500     0.506801
15     3913           3     0.766001       0.787155    0.618112     0.626518
16     3913           7     0.777467       0.819702    0.621591     0.673084
17     3913          11     0.786938       0.834942    0.630898     0.671470
18     3917           3     0.752997       0.752990    0.558248     0.543063
19     3917           7     0.792358       0.808470    0.555097     0.560922

In [39]:
df.describe()

,dataset,neighbours,accuracy_sk,accuracy_mod,roc_auc_sk,roc_auc_mod
count,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000
mean,6916.666667,7.000000,0.821772,0.837267,0.690514,0.704511
std,4365.094812,3.296654,0.104838,0.090042,0.164316,0.160500
min,31.000000,3.000000,0.619000,0.631000,0.499192,0.498872
25%,3903.000000,3.000000,0.747046,0.799887,0.551844,0.543870
50%,9928.000000,7.000000,0.812129,0.824973,0.648590,0.718136
75%,9976.000000,11.000000,0.916843,0.916241,0.805747,0.808849
max,14952.000000,11.000000,1.000000,0.997086,1.000000,0.997215

### Results of Modified KNN on binary datasets

In general, the modified knn applied into binary datasets presented, in average, 1,1% more eficiency in accuracy metric, and 1% more eficiency in roc_auc metric. Now, we need to figure out in each subset it works better and worst.

In [69]:
balanced_df = df[df['dataset'].isin([3, 15, 29, 31, 37, 43, 49, 219, 9910, 9946, 9957, 9976, 10093, 14952])]
balanced_df_n3 = balanced_df[balanced_df['neighbours'] == 3]
balanced_df_n7 = balanced_df[balanced_df['neighbours'] == 7]
balanced_df_n11 = balanced_df[balanced_df['neighbours'] == 11]

In [70]:
disbalanced_df = df[df['dataset'].isin([3021, 3902, 3903, 3904, 3913, 3917, 3918, 7592, 9952, 9971, 9977, 9978, 10101])]
disbalanced_df_n3 = disbalanced_df[disbalanced_df['neighbours'] == 3]
disbalanced_df_n7 = disbalanced_df[disbalanced_df['neighbours'] == 7]
disbalanced_df_n11 = disbalanced_df[disbalanced_df['neighbours'] == 11]

In [71]:
balanced_df_n3.describe()

,dataset,neighbours,accuracy_sk,accuracy_mod,roc_auc_sk,roc_auc_mod
count,9.000000,9.0,9.000000,9.000000,9.000000,9.000000
mean,7216.111111,3.0,0.809421,0.837023,0.790457,0.816810
std,5618.921570,0.0,0.130194,0.110632,0.153834,0.138156
min,31.000000,3.0,0.619000,0.631000,0.514524,0.524048
25%,43.000000,3.0,0.702692,0.804612,0.702692,0.781667
50%,9946.000000,3.0,0.799398,0.811176,0.791289,0.805997
75%,9976.000000,3.0,0.929699,0.931485,0.918690,0.921955
max,14952.000000,3.0,1.000000,0.997086,1.000000,0.997215

In [72]:
balanced_df_n7.describe()

,dataset,neighbours,accuracy_sk,accuracy_mod,roc_auc_sk,roc_auc_mod
count,9.000000,9.0,9.000000,9.000000,9.000000,9.000000
mean,7216.111111,7.0,0.820045,0.840717,0.797001,0.816332
std,5618.921570,0.0,0.117357,0.102373,0.146910,0.136669
min,31.000000,7.0,0.652000,0.656000,0.524762,0.522857
25%,43.000000,7.0,0.737030,0.799180,0.734615,0.777325
50%,9946.000000,7.0,0.801137,0.823846,0.792821,0.809619
75%,9976.000000,7.0,0.926222,0.933271,0.914852,0.922608
max,14952.000000,7.0,1.000000,0.991246,1.000000,0.991305

In [73]:
balanced_df_n11.describe()

,dataset,neighbours,accuracy_sk,accuracy_mod,roc_auc_sk,roc_auc_mod
count,9.000000,9.0,9.000000,9.000000,9.000000,9.000000
mean,7216.111111,11.0,0.821751,0.843027,0.797702,0.819104
std,5618.921570,0.0,0.114913,0.099923,0.147486,0.134653
min,31.000000,11.0,0.664000,0.669000,0.521905,0.531190
25%,43.000000,11.0,0.749930,0.802007,0.745472,0.779364
50%,9946.000000,11.0,0.793534,0.825454,0.783759,0.819362
75%,9976.000000,11.0,0.929762,0.933302,0.919830,0.920880
max,14952.000000,11.0,1.000000,0.994166,1.000000,0.994260

In [76]:
balanced_df_n7

    dataset  neighbours  accuracy_sk   accuracy_mod  roc_auc_sk  roc_auc_mod
1        31           7     0.652000       0.656000    0.524762     0.522857
4        37           7     0.737030       0.817772    0.690732     0.784254
7        43           7     0.801137       0.799180    0.792821     0.777325
25     9910           7     0.755535       0.773930    0.751580     0.770029
28     9946           7     0.926222       0.933271    0.914852     0.922608
34     9957           7     0.814034       0.824492    0.805026     0.809619
40     9976           7     0.734615       0.823846    0.734615     0.823846
46    10093           7     1.000000       0.991246    1.000000     0.991305
52    14952           7     0.959829       0.946715    0.958617     0.945149